"""Initial schema

Revision ID: 4c90faaf3aec
Revises: 
Create Date: 2026-08-19 18:47:51.035355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c90faaf3aec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('working_days_per_month', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('working_days_per_month BETWEEN 1 AND 31', name='working_days_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_currency'), 'scenarios', ['currency'], unique=False)
    op.create_table('fixed_costs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('category', sa.Enum('RENT', 'SALARY', 'ZUS', 'UTILITIES', 'TAX', 'INSURANCE', 'OTHER', name='costcategory', native_enum=False), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_costs_scenario_id'), 'fixed_costs', ['scenario_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('purchase_unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', name='unit', native_enum=False), nullable=False),
    sa.Column('unit_size', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_scenario_id'), 'ingredients', ['scenario_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('wastage_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_scenario_id'), 'products', ['scenario_id'], unique=False)
    op.create_table('seasonality_factors',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='month_range'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'month')
    )
    op.create_table('traffic_assumptions',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('daily_customers', sa.Integer(), nullable=False),
    sa.Column('avg_products_per_customer', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('recipe_items',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', name='unit', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_items')
    op.drop_table('traffic_assumptions')
    op.drop_table('seasonality_factors')
    op.drop_index(op.f('ix_products_scenario_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ingredients_scenario_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_fixed_costs_scenario_id'), table_name='fixed_costs')
    op.drop_table('fixed_costs')
    op.drop_index(op.f('ix_scenarios_currency'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
