"""add expected_sales_share to product

Revision ID: ee4f06d27d9f
Revises: 4c90faaf3aec
Create Date: 2026-09-01 10:03:04.840052

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ee4f06d27d9f"
down_revision: str | Sequence[str] | None = "4c90faaf3aec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
