"""Add expected_sales_share to products

Revision ID: f97ec4ba70f4
Revises: 7af64f59e244
Create Date: 2026-09-10 15:08:37.059467

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f97ec4ba70f4"
down_revision: str | Sequence[str] | None = "7af64f59e244"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
